/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_parkir;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Assalam
 */
public class Form_petugas extends javax.swing.JFrame {

    DefaultTableModel tab;
    koneksi konek = new koneksi();
    private Connection connect;

    /**
     * Creates new form Form_petugas
     */
    public Form_petugas() {
        initComponents();
        konek.koneksi();
        tampilkan();
        setLocationRelativeTo(null);
        btn_simpan.setBackground(Color.GREEN.BLACK);
        btn_Edit.setBackground(Color.GREEN.BLACK);
        btn_hapus.setBackground(Color.GREEN.BLACK);
        btn_kembali.setBackground(Color.GREEN.BLACK);
    }

    public void tampilkan() {
        tab = (DefaultTableModel) tbForm.getModel();
        tab.setRowCount(0);
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT id_pegawai,kode, nama_pegawai, no_hp, email FROM petugas";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                String ID = konek.rs.getString("id_pegawai");
//                String Kode = konek.rs.getString("kode");
                String nama = konek.rs.getString("nama_pegawai");
                String noHp = konek.rs.getString("no_hp");
                String email = konek.rs.getString("email");

                String[] data = {ID, nama, noHp, email};
                tab.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Gagal Ambil Data" + e);
        }
        tbForm.setModel(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_noHp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_email = new javax.swing.JTextArea();
        btn_simpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbForm = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 107, 40, 14);

        txt_nama.setBackground(new java.awt.Color(204, 204, 204));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama);
        txt_nama.setBounds(60, 100, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Hp");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 133, 40, 14);

        txt_noHp.setBackground(new java.awt.Color(204, 204, 204));
        txt_noHp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_noHp.setBorder(null);
        txt_noHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noHpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_noHp);
        txt_noHp.setBounds(60, 130, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 161, 40, 14);

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setColumns(20);
        txt_email.setRows(5);
        txt_email.setBorder(null);
        jScrollPane1.setViewportView(txt_email);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(57, 161, 171, 92);

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon("F:\\Tugas Kuliah\\BASIS DATA\\UAS Basis Data\\TA_parkir\\save.png")); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(57, 268, 90, 20);

        tbForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "No HP", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFormMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbForm);
        if (tbForm.getColumnModel().getColumnCount() > 0) {
            tbForm.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(238, 40, 452, 275);

        btn_hapus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon("F:\\Tugas Kuliah\\BASIS DATA\\UAS Basis Data\\TA_parkir\\clear.png")); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(60, 300, 90, 20);

        btn_kembali.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(160, 300, 67, 21);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FORM PETUGAS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 30, 175, 31);

        btn_Edit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon("F:\\Tugas Kuliah\\BASIS DATA\\UAS Basis Data\\TA_parkir\\edit.png")); // NOI18N
        btn_Edit.setText("Edit");
        btn_Edit.setBorder(null);
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Edit);
        btn_Edit.setBounds(160, 270, 69, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kode");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 81, 28, 14);

        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_kode);
        txt_kode.setBounds(62, 78, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Tugas Kuliah\\BASIS DATA\\UAS Basis Data\\TA_parkir\\ff.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 700, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_noHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noHpActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if (txt_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama belum diisi!");
            txt_nama.requestFocus();
        } else if (txt_noHp.getText().trim().equals("")) {
            txt_noHp.requestFocus();
        } else if (txt_email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Email belum diisi");
            txt_email.requestFocus();
        } else {
            String nama_pegawai = "", no_hp = "", email = "";
            nama_pegawai = txt_nama.getText();
            String kode = txt_kode.getText();
            no_hp = txt_noHp.getText();
            email = txt_email.getText();
            try {
                connect = new koneksi().getKoneksi();
                String query
                        = "INSERT INTO petugas (kode, nama_pegawai, no_hp, email) VALUES(?,?,?,?)";

                PreparedStatement psmt = connect.prepareStatement(query);
                psmt.setString(1, kode);
                psmt.setString(2, nama_pegawai);
                psmt.setString(3, no_hp);
                psmt.setString(4, email);

                psmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Menyimpan Data Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampilkan();

            } catch (Exception e) {
                System.out.println("Menyimpan Data Gagal " + e);
            }
        }


    }//GEN-LAST:event_btn_simpanActionPerformed
            
            
            
            
            
    

    private void tbFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFormMouseClicked
        Clicked();
    }//GEN-LAST:event_tbFormMouseClicked

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
            String id_pegawai = "", nama_pegawai = "", no_hp = "", email = "";
            nama_pegawai = txt_nama.getText();
            String Kode = txt_kode.getText();
            no_hp = txt_noHp.getText();
            email = txt_email.getText();
            try {
                connect = new koneksi().getKoneksi();
                String query
                        = "UPDATE petugas SET nama_pegawai = ?, no_hp = ?, email=? where id_pegawai=? ";

                PreparedStatement psmt = connect.prepareStatement(query);
                psmt.setString(1, nama_pegawai);
                psmt.setString(2, no_hp);
                psmt.setString(3, email);
                psmt.setString(4, Kode);
                System.out.println(psmt);
                
                psmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Menyimpan Data Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampilkan();

            } catch (Exception e) {
                System.out.println("Menyimpan Data Gagal " + e);
            }
        


    }//GEN-LAST:event_btn_EditActionPerformed

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        String kode_petugas ="";
        kode_petugas = txt_kode.getText();
        try{
            connect = new koneksi().getKoneksi();
            String query = "Delete from petugas where id_pegawai = ?";
            PreparedStatement psmt = connect.prepareStatement(query);
            psmt.setString(1, kode_petugas);
            psmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
            tampilkan();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Maaf anda gagal hapus data");
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        new Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed
public void Clicked(){
    int row = tbForm.getSelectedRow();
        txt_kode.setText((String) tbForm.getValueAt(row, 0));
        txt_nama.setText((String) tbForm.getValueAt(row, 1));
        txt_noHp.setText((String) tbForm.getValueAt(row, 2));
        txt_email.setText((String) tbForm.getValueAt(row, 3));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_petugas.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_petugas.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_petugas.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_petugas.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbForm;
    private javax.swing.JTextArea txt_email;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_noHp;
    // End of variables declaration//GEN-END:variables
}
